name: Test Go

on:
  pull_request:
    paths:
      - 'go/**'
jobs:
  test_unix:
    name: Go tests
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.19
        id: go
      - uses: actions/checkout@v2
      - name: Test All
        working-directory: ./go
        run: go test ./...
