name: Test Go

on:
  pull_request:
    paths:
      - 'go/**'
jobs:
  test_unix:
    name: Go tests ${{ matrix.dolt_fmt }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        dolt_fmt: ["", "__DOLT__"]
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ^1.19
        id: go
      - uses: actions/checkout@v3
      - name: Test All
        working-directory: ./go
        run: go test ./...
        env:
          DOLT_DEFAULT_BIN_FORMAT: ${{ matrix.dolt_fmt }}
